# Generated by Django 2.2 on 2019-04-06 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('birth_day', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=20, verbose_name='Телефон')),
                ('begin_work', models.DateTimeField(auto_now_add=True)),
                ('end_work', models.DateTimeField(blank=True, null=True)),
                ('Position', models.CharField(max_length=30, verbose_name='Должность')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeBase.Department', verbose_name='Департамент')),
            ],
        ),
    ]
