# Generated by Django 2.2 on 2019-04-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='begin_work',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_work',
            field=models.DateField(blank=True, null=True),
        ),
    ]
